# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 14.x
        
      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - uses: "appleboy/scp-action@master"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}          
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLWs8mBiu/9fEUDn5lU97xxbTBE1zOzQKHUuyFedP6FPq9WCjBzgUbFsr+Nh8/dWKTofReX/YjkRsl9wm6IKFYQgi2QmiUgELeFrmwO5wl2U4zYb/Yo+1JmbvfIVNb0Ub22K4YEeFGWfvIwCIiGtVY2umFoOWcjSWpOS20+CIrIMQKS4Ju4ToumiS0ZqESAdkvdUpCR799RPab6X4q5l2eEvE64i1MTOBGB3L9SdhLrFZtACkI98zQuQRUlNYBolN79AaEylb6PEqgBuq88Xcrq/Hw1q6RZVss8N0Panyw9CBHnkUOz1hafhXjw/n8fH9AITJg2fv4gyjdY2+twz+hJqY0pVCv+R1JoXZG5MjF8+BHNkAlfjCPwzQ0HJWNcQkjMX8gNl1qkZRdS9zn1J7Uk95jiSWylihNCLlIIVcygTIfmQsoNRRSEgWCJ3XQp57FLLUvCLVkW406Zp8JBq9dRsB/rahXsN8DmOQ+XRJEZk46pHOK+FFwmEAf7vjZDKU= diogodesouza@Diogos-MacBook-Pro.local
          source: "., !node_modules"
          target: "test"
      

